version: '3.4'

services:
  celebrator:
    image: ${DOCKER_REGISTRY-}celebrator
    build:
      context: .
      dockerfile: celebrator/Dockerfile
    environment:
      - ConnectionStrings__MsSqlConnection=Server=mssql_server;Database=PersonsDB;User=sa; Password=1q2w3e4r+;
    ports:
      - "8443:443"
  mssql_server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "1q2w3e4r+"
      MSSQL_PID: Express
    ports:
      - "1433:1433"